### ISSUE TITLE
[ JCON_SERVER ] Create jcon_server interface.

### ISSUE THREAD

**Issue by gnarrf95** [gnarrf95/libjayc#14]
Create a server system (similar to _jcon\_client_),
that listens to a server and creates instances
of _jcon\_thread_ for each new connection.

**Tasks:**
- [x] General server interface.
- [x] Implement linked list, to store client connections.
- [x] Use `jcon_thread_data_handler_t` to implement data management.
- [x] Create control thread, that listens to server, creates connections and destroys disconnected clients.
- [x] Fix structure of code (split into server-handler and server-functionality ?). --> _Create seperate components!_
